services:
  # ---------------- BACKEND ----------------
  - type: web
    name: issue-tracker-server
    env: node
    plan: free
    region: ohio
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          type: static
          name: issue-tracker-client
          property: url

  # ---------------- FRONTEND ----------------
  - type: static
    name: issue-tracker-client
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: issue-tracker-server
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
